import React, { useState } from "react";

const tracks = [
  "Acorn Heights",
    "Airship Fortress",
      "Boo Cinema",
        "Bowser's Castle",
          "Cheep Cheep Falls",
            "Choco Mountain",
              "Crown City",
                "Dandelion Depths",
                  "Desert Hills",
                    "Dino Dino Jungle",
                      "DK Pass",
                        "DK Spaceport",
                          "Dry Bones Burnout",
                            "Faraway Oasis",
                              "Great ? Block Ruins",
                                "Koopa Troopa Beach",
                                  "Mario Bros. Circuit",
                                    "Mario Circuit",
                                      "Moo Moo Meadows",
                                        "Peach Beach",
                                          "Peach Stadium",
                                            "Rainbow Road",
                                              "Salty Salty Speedway",
                                                "Shy Guy Bazaar",
                                                  "Sky-High Sundae",
                                                    "Starview Peak",
                                                      "Toad's Factory",
                                                        "Wario Stadium",
                                                          "Wario's Galleon",
                                                            "Whistlestop Summit",
                                                            ];

                                                            export default function MarioKartLogger() {
                                                              const [track, setTrack] = useState("");
                                                                const [placement, setPlacement] = useState("");
                                                                  const [roomSize, setRoomSize] = useState("");
                                                                    const [entries, setEntries] = useState([]);
                                                                      const [error, setError] = useState("");
                                                                        const [view, setView] = useState("form"); // "form" or "history"

                                                                          const handleSubmit = (e) => {
                                                                              e.preventDefault();

                                                                                  const placementNum = parseInt(placement, 10);
                                                                                      const roomSizeNum = parseInt(roomSize, 10);

                                                                                          if (
                                                                                                !track ||
                                                                                                      isNaN(placementNum) ||
                                                                                                            isNaN(roomSizeNum) ||
                                                                                                                  placementNum < 1 ||
                                                                                                                        placementNum > 24 ||
                                                                                                                              roomSizeNum < 1 ||
                                                                                                                                    roomSizeNum > 24
                                                                                                                                        ) {
                                                                                                                                              setError("Please enter valid values (1–24 for placement and room size).");
                                                                                                                                                    return;
                                                                                                                                                        }

                                                                                                                                                            const newEntry = {
                                                                                                                                                                  track,
                                                                                                                                                                        placement: placementNum,
                                                                                                                                                                              roomSize: roomSizeNum,
                                                                                                                                                                                    id: Date.now(),
                                                                                                                                                                                        };

                                                                                                                                                                                            setEntries([...entries, newEntry]);
                                                                                                                                                                                                setTrack("");
                                                                                                                                                                                                    setPlacement("");
                                                                                                                                                                                                        setRoomSize("");
                                                                                                                                                                                                            setError("");
                                                                                                                                                                                                              };

                                                                                                                                                                                                                const deleteEntry = (id) => {
                                                                                                                                                                                                                    setEntries(entries.filter((entry) => entry.id !== id));
                                                                                                                                                                                                                      };

                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                            <div style={{ padding: "20px", fontFamily: "sans-serif" }}>
                                                                                                                                                                                                                                  <nav style={{ marginBottom: "20px" }}>
                                                                                                                                                                                                                                          <button onClick={() => setView("form")}>Add Result</button>
                                                                                                                                                                                                                                                  <button onClick={() => setView("history")} style={{ marginLeft: "10px" }}>
                                                                                                                                                                                                                                                            View History
                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                          </nav>

                                                                                                                                                                                                                                                                                {view === "form" && (
                                                                                                                                                                                                                                                                                        <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                              <label>
                                                                                                                                                                                                                                                                                                                            Track:
                                                                                                                                                                                                                                                                                                                                          <select value={track} onChange={(e) => setTrack(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                          <option value="">-- Select a track --</option>
                                                                                                                                                                                                                                                                                                                                                                          {tracks.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                            <option key={t} value={t}>
                                                                                                                                                                                                                                                                                                                                                                                                                {t}
                                                                                                                                                                                                                                                                                                                                                                                                                                  </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Placement:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={placement}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setPlacement(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        min="1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        max="24"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Room Size:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={roomSize}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setRoomSize(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              min="1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              max="24"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {error && <p style={{ color: "red" }}>{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="submit">Add Result</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {view === "history" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Race History</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {entries.length === 0 && <p>No entries yet.</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {entries.map((entry) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li key={entry.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {entry.track} — {entry.placement}/{entry.roomSize}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => deleteEntry(entry.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ marginLeft: "10px" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Delete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        